### PR TITLE
native,testlapack: fix bounding of cleanup

### LINKED ISSUE #267: native: Dggsvp3 incorrectly calculates range for A cleanup
If a test is run with m=3, p=3, n=5 the code at [line 264](https://github.com/gonum/lapack/blob/master/native/dggsvp3.go#L264) panics with a bounds check failure.

```
--- FAIL: TestDggsvp3 (0.00s)
panic: runtime error: slice bounds out of range [recovered]
	panic: runtime error: slice bounds out of range

goroutine 5 [running]:
testing.tRunner.func1(0xc4200724e0)
	/home/daniel/Development/go/src/testing/testing.go:622 +0x29d
panic(0x6a1fc0, 0x895c00)
	/home/daniel/Development/go/src/runtime/panic.go:489 +0x2cf
github.com/gonum/lapack/native.Implementation.Dggsvp3(0x515655, 0x3, 0x3, 0x5, 0xc420080980, 0xf, 0xf, 0x5, 0xc420080a80, 0xf, ...)
	/home/daniel/Development/src/github.com/gonum/lapack/native/dggsvp3.go:264 +0xcf0
github.com/gonum/lapack/native.(*Implementation).Dggsvp3(0x8b84e8, 0x515655, 0x3, 0x3, 0x5, 0xc420080980, 0xf, 0xf, 0x5, 0xc420080a80, ...)
	<autogenerated>:25 +0x28b
github.com/gonum/lapack/testlapack.Dggsvp3Test(0xc4200724e0, 0x857340, 0x8b84e8)
	/home/daniel/Development/src/github.com/gonum/lapack/testlapack/dggsvp3.go:109 +0xd20
github.com/gonum/lapack/native.TestDggsvp3(0xc4200724e0)
	/home/daniel/Development/src/github.com/gonum/lapack/native/lapack_test.go:116 +0x5b
testing.tRunner(0xc4200724e0, 0x6e5600)
	/home/daniel/Development/go/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/home/daniel/Development/go/src/testing/testing.go:697 +0x2ca
FAIL	github.com/gonum/lapack/native	0.005s
```

### PR DESCRIPTION
**Pull request by kortschak**
@btracey @vladimir-ch Please take a look.

Fixes #267.

### CODE REVIEW

File: native/dggsvp3.go [hunk 1]
```diff
@@ -260,7 +260,7 @@ func (impl Implementation) Dggsvp3(jobU, jobV, jobQ lapack.GSVDJob, m, p, n int,
 		}
 
 		// Clean up A.
-		for i := k + 1; i < k+l; i++ {
+		for i := k + 1; i < min(m, k+l); i++ {
```
Comment (vladimir-ch) [inline native/dggsvp3.go]: I'm still not convinced that this is completely correct. If k+l<m, then this loop will not zero out the bottom right block in A, unlike in the reference.

Comment (kortschak) [inline native/dggsvp3.go]: I don't think it really matters (I don't think the elements of the block at A[k+l:m, n-l:n] are referenced later, but I will change to make sure they are zeroed.

Comment (vladimir-ch) [inline native/dggsvp3.go]: The docs promise that it will be zero, so it's nice to keep that promise. We should really have a way to create bad matrices for testing.

**Comment by kortschak** [comment]
PTAL

File: native/dggsvp3.go [hunk 2]
```diff
@@ -260,8 +260,8 @@ func (impl Implementation) Dggsvp3(jobU, jobV, jobQ lapack.GSVDJob, m, p, n int,
 		}
 
 		// Clean up A.
-		for i := k + 1; i < k+l; i++ {
-			r := a[i*lda+n-l : i*lda+i-k+n-l]
+		for i := k + 1; i < m; i++ {
+			r := a[i*lda+n-l : i*lda+min(i-k+n-l, n)]
```
Comment (vladimir-ch) [inline native/dggsvp3.go]: Just a nit: if it were written as `n-l+i-k`, then (at least for me) it's easier to see that `n-l` is a fixed offset and `i-k` a variable index, and what the loop does.

Comment (kortschak) [inline native/dggsvp3.go]: Yes, I noticed that before, and then forgot when I was fixing this. I'll do that now.
